<?php
namespace App\Services\PollingUnit\Isa;
	
	class Isa_South
	{
		
		function __construct()
		{
			# code...
			$this->pollingUnits =  $this->pollingUnits();
		}

		public function pollingUnits(){
			return [
				'KWANAR ISA, PRI. SCH.',
				'KURAR MOTA, PRI. SCH.',
				'SHIYAR DANBALABE MAITANSU PRI. SCH.',
				'UNDER GAWO TREE NEAR BOREHOLE MAIGARKE (SHIYAR DAN BALARABE MAI GARKE)',
				'SARDAUNA PRI SCH. (SHIYAR BALARABE YAR MAKAFI)',
				'SHIYAR DANBALARABE, SARDAUNA PRI. SCH.',
				'UNDER NEEM TREE YAR KASUWA MAGAJI (SHIYAR GAJO YAKASUWA MAGAJI)',
				'FILIN RIJIYA KUDA ALLAH (SH/GAJO KUDA ALLAH G/A SUK SEC)',
				'BAKIN TITI (GIDAN SEC.ILYASU)',
				'DAN MALIKI PRI SCH. (GARKAR SAKATARE ISA,KUSADA GIDAN SAKATARE)',
				'SHALLAMAWA , SHALLAMAWA',
				'BAKIN TITI HERAMA (HEREMA GIDAN ALHAJI JIJJI)',
				'BAKIN TITI (YAR KASUWA GIDAN TUDU SHOP)',
				'FILIN RIJIYA BOREHOLE DUDAKIN (SHIYAR MUHAMMAD DUDAKE)',
				'GARIN HASSAN',
				'SHIYAR D/B MAITANBU P/SCHOOL'
			];
		}
	}