<?php

namespace App\Services\PollingUnit\SokotoNorth;
/**
* this class will return polling Units of the class
*/
class MagajinGariB
{
	
	function __construct()
	{
		$this->pollingUnits = $this->PollingUnits();
	}

	public function pollingUnits()
	{
		return [
			'SH/ARZIKA WAKILI',
			'G/LADAN LOCAL GOVT I',
			'G/LADAN LOCAL GOVT II',
			'SHIYAR HAKIMI JELANI ‐ SH/HAKIMI JELANI',
			'SHIYAR HAKIMI BALA',
			'SHYAR /CHIKA FANTA',
			'SH/ALH.DAHIRU',
			"KOFAR KADE SALIHU ANKA PRIMARY SCHOOL I (SHIYAR D/FARIJO 'A')",
			"KOFAR KADE SALIHU ANKA PRIMARY SCHOOL II (SHIYAR D/FARIJO 'B')",
			'SH/ABDUL SODANGI',
			'G/INNO YARGWAMNA',
			'NEAR MASALLACIN GARKAR ALH. YUSUF SA’IDU (G/ISA SHEHU KAMBA)',
			'MAGAJIN GARI M.P.S',
			'SHIYAR TSUHO AMALI',
			'MARINA ASADA',
			'SHIYAR HAKIMI BARMO I',
			'NEAR YAHAYA ASADA HOUSE (SHIYAR HAKIMI BARMO II)',
			'SHIYAR SULE ZORAMAWA I',
			'SHIYAR SULE ZORAMAWA II',
			'G/KASIMU TELA I',
			'G/KASIMU TELA ‐ II',
			'SH/SHARU MAIKUSA',
			'DAN FILI NUFAWA I',
			'DAN FILI NUFAWA II',
			'SH/SHEHU KAMBA',
			'CIMMO ASADA',
			'BEHIND JUMU’AT MOSQUE KUFFA AREA (KUFFA)',
			'RUMBU PRIMARY SCHOOL I (SHIYAR ABDU MAI KIFI I)',
			'RUMBU PRIMARY SCHOOL II (SHIYAR ABDU MAI KIFI II)',
			'SH/HAKIMI BULU',
			'SHIYAR DAN INNA TELA'
		];
	}
}
