<?php

namespace App\Services\PollingUnit\SokotoNorth;
/**
* this class will return polling Units of the class
*/
class WaziriB
{
	
	function __construct()
	{
		$this->pollingUnits = $this->PollingUnits();
	}

	public function pollingUnits()
	{
		return [
            'GIDAN IGE MALAU',
			'GIDAN IGE MALAU',
			'OPEN SPACE GARKAR MAGAJIN WAZIRI (RIJIYAR BAZZAI)',
			'GIDAN MALAM SODANGI',
			'GARKAR NAWADU',
			'GIDAN HASSAN STORE',
			'GIDAN MARAFAN KWANNA I',
			'EASTERN PART OF A MOSQUE ALON KOFAR RINI MARKET (GIDAN MARAFAN KWANNA II)',
			'NIZZAMIYYA PRIMARY SCHOOL (GIDAN WAZIRIN SOKOTO)',
			'SHIYAR SARKIN SHANU',
			'GIDAN YUSUF BILYA',
			'WAZIRI MODEL PRIMARY SCHOOL I(GIDAN BARADE K/RINI A)',
			'WAZIRI MODEL PRIMARY SCHOOL II(GIDAN BARADE K/RINI B)',
			'SHIYAR ABBAS DANGALADIMA',
			'SHIYAR BELLO IBRAHIM',
			'TUDUN UBAN DOMA',
			'WAZIRI MODEL PRIMARY SCHOOL III(GARKAR GARBA JABO)',
			'OFFISHIN HAKIMI',
			'OFFISHIN HAKIMI ‐ GIDAN DAN BATURE',
			'NEAR GARKAR IGIN DAN TUNKA (RIJIYAR BAZZA II)'
		];
	}
}
