<?php

namespace App\Services\PollingUnit\SokotoSouth;
/**
* this class will return the pollin unit of the class
*/
class S_A_K_Atiku
{
	
	function __construct()
	{
		$this->pollingUnits = $this->pollingUnits();
	}

	protected function pollingUnits()
	{
		return [
			'SARKIN ADAR K/ATIKU MASALLACI YARBAWA I',
			'SARKIN ADAR K/ATIKU MASALLACI YARBAWA II',
			'SARKIN ADAR OFISHIN HAKIMI A/ROAD',
			'SARKIN ADAR OFISHIN HAKIMI ATIKU/ROAD',
			'SARKIN ADAR KWAMBERU I',
			'SARKIN ADAR KWAMBERU II',
			'SARKIN ADAR S/MALLAMMAI',
			'SARKIN ADAR GARKAR LULA RUNGUMI I',
			'SARKIN ADAR GARKAR LULA RUNGUMI II',
			'SARKIN ADAR GARKAR BALA R/ZAURE',
			'SARKIN ADAR GARKAR SALANKE GIDAN SALANKE',
			'SARKIN ADAR GARKAR BELLOW ISA G/KANAWA',
			'SARKIN ADAR GARKAR A.DANDARE G/KANAWA',
			'SARKIN ADAR GARKAR LADAN RUNGUMI',
			'SARKIN ADAR GARKAR ALI SHINA I',
			'SARKIN ADAR GARKAR ALI SHINA II',
			'SARKIN ADAR GARKAR SHEHU NARAME I',
			'SARKIN ADAR GARKAR SHEHU NARAME II',
			'S/A/K/ATIKU GIWA CHEMIST',
			'S/A/K/ATIKU GARKAR UBAN DOMA'
		];
	}
}