<?php

namespace App\Services\PollingUnit\SokotoSouth;
/**
* this class will return the pollin unit of the class
*/
class SarkinAdarKwanni
{
	
	function __construct()
	{
		$this->pollingUnits = $this->pollingUnits();
	}

	protected function pollingUnits()
	{
		return [
			'G.MAIFADA I',
			'G.MAIFADA II',
			'MARAFAN KINANNI I',
			'MARAFAN KINANNI II',
			'HAKIMI TSOHO',
			'G.TAMBARI TSOHO',
			'TAMBARI TSOHO',
			'S/YAKI BINJI',
			'G/B DAN KOLI',
			'BELLO KAFINTA',
			'SARKIN ADAR UMARU SHUGABA JEGAWA I',
			'SARKIN ADAR UMARU SHUGABA JEGAWA II',
			'SARKIN ADAR GALADIMA JOHN HOLT',
			'SARKIN ADAR GARKA INUWA I',
			'SARKIN ADAR GARKA INUWA II',
			'GIDAN AKAWU JEGAWA I',
			'GARKA AKAWU JEGAWA II',
			'SARKIN ADAR GARKA LONGMAN T/TASHA',
			'SARKIN ADAR HAMZA MAIUNGUWA KWANI',
			'SARKIN ADAR SIDI MAMMAN ASARAKAWA T/TASHA',
			'SARKIN ADAR BATUREN KAJI JEGAWA',
			'SARKIN ADAR G/UMARU POLICE STATION',
			'SARKIN ADAR MAIUNGUWA MAINIYO I',
			'SARKIN ADAR MAIUNGUWA MAINIYO II',
			'SARKIN ADAR GARKA ALIYU KOKO KWANI',
			'SARKIN ADAR KWANNI POLICE STATION G/UMARU',
			'SARKIN ADAR KWANNI SAC I',
			'SARKIN ADAR KWANNI SAC II'
		];
	}
}