<?php
namespace App\Services\PollingUnit\Gwadabawa;
	
	class AsaraArewa
	{
		
		function __construct()
		{
			# code...
			$this->pollingUnits =  $this->pollingUnits();
		}

		public function pollingUnits(){
			return [
				'SHIYAR HAKIMI, FADAN KAI',
				'GARI, MAMMAN SUKA',
				'PRIMARY SCHOOL GIDAN ANAZAR (TSAKAR GARI GIDAN ANAZAR)',
				'UNDER THREE SHADE, ZANGO NAHANTSI OPEN SPACE (TSAKAR GARI ZANGO N/HANTSI)',
				'PRIMARY SCHOOL, BAUDA (PRIMARY SCHOOL BAUDA)',
				'CENTRAL MOSQUE, BAKIN MASALACI, MAKINA ALFARMA OPEN SPACE (BAKIN MASALACI MAKINA ALFARMA)',
				'DISPENSARY MAKINA MAIFUCHI (TSAKAR GARI MAKINA M/FUCHI)',
				'PRIMARY SCHOOL HURA/MAGAMA (PRIMARY SCHOOL HURA HURA/MAGAMA)',
				'PRIMARY SCHOOL MUWAILA (PRY SCH. T. MUWAILA, TUDUN MUWAILA)',
				'SHIYAR HAKIMI, MAMAN SUKA GARI',
				'PRIMARY SCHOOL MAMMAN SUKA (PRI. SCH. M. SUKA G. GEZA)',
				'UNDER THREE SHADE, TSAKAR GARI OPEN SPACE (TSAKAR GARI MALLAMAWA KAGALABA.)',
				'DISPENSARY, FADAN KAI',
				'SHIYAR HAKIMI, MAKINA ALFARMA'
			];
		}
	}