<?php
namespace App\Services\PollingUnit\Gwadabawa;
	
	class AsaraKudu
	{
		
		function __construct()
		{
			# code...
			$this->pollingUnits =  $this->pollingUnits();
		}

		public function pollingUnits(){
			return [
				'SHIYAR MAGAJI',
				'OPPOSITE HOSPITAL, OPEN SPACE (SHIYAR GALADIMA, SH GAL.)',
				'PRIMARY SCHOOL MAKARANTA, SHIYAR GALADIMA (MAKARANTA SH. GALADIMA)',
				'PRIMARY SCHOOL MAKARANTA, TUNGAR MADUGU (MAKARANTA TUNGAR MADUGU)',
				'OPPOSITE ISLAMIYYA, OPEN SPACE (MAKARANTA TUNGAR KWANGI)',
				'TREE SHADE, OPEN SPACE DANFILI, RUMBUJE (DAN FILI RUMBUJE)',
				'PRIMARY SCHOOL MAKARANTA/T/TUDU BUGA (MAKARANTA T/TUDU BUGA)',
				'PRIMARY SCHOOL MAKARANTA /RANGANDAWA (MAKRANTA/ RANGANDAWA)',
				'UNDER TREE SHADE ,NEAR MOSQUE DANFILI, AGAJIBA (DAN FILI AGAJIBA)',
				'PRIMARY SCHOOL MAKARANTA, KARANBI (MAKARANTA KARANBI)',
				'CLOSE TO WELL, OPEN SPACE KWAREN GEZU (DAN FILI KWAREN GEZU)',
				'UNDER TREE SHADE, OPEN SPACE GIDAN ALFARMA, DAKWALE MAYEL (GIDAN ALFARMA DAKWALLE, MAYEL)',
				'PRIMARY SCHOOL TUNGAR RAFI (SHIYAR HAKIMI, TUNGAR RAFI)',
				'PRIMARY SCHOOL TUNGAR KURFAI (DANFILI, TUNGAR KURFAI)',
				'TSAKAR GARI, TUNGAR KWANGI',
				'T/KWACI‐DAN FILI'
			];
		}
	}