<?php
namespace App\Services\PollingUnit\Gwadabawa;
	
	class ChimmolaArewa
	{
		
		function __construct()
		{
			# code...
			$this->pollingUnits =  $this->pollingUnits();
		}

		public function pollingUnits(){
			return [
				'MATSE, MATSE',
				'NEAR JUMUAT MOSQUE HERE (HERE, HERE/ GALA)',
				'NEAR JUMUAT MOSQUE SHIYAR LIMAN (SHIYAR LIMAN, TAMBAGARKA SH LIMAN)',
				'NEAR MOSQUE SHIYAR DAN ORO (SHIYAR DAN ORO)',
				'UNDER TREE SHADE, SHIYAR KAURA OPEN SPACE (SHIYAR KAURA)',
				'PRIMARY SCHOOL, KALABA (KALABA, KALABA)',
				'UNDER TREE SHADE (SHIYAR HAKIMI, ADANGERO/RANGANDAW)',
				'PRIMARY SCHOOL (KASUWA TUNGA MALAM RASHIDU)',
				'PRI. SCH. (SHIYAR HAKIMI, KAGOYE/ADOSA)',
				'UNDER TREE SHADE, WADAI OPEN SPACE (WADAI PRI. SCH. )',
				'UNDER TREE SHADE TATAYE (TATAYE PRY SCH. )',
				'UNDER TREE SHADE SHIYAR UBAN DAWAKI (SHIYAR UBANDAWAKI)',
				'UNDER TREE SHADE SH S.FULANI I (SHIYAR S/FULANI I)',
				'UNDER TREE SHADE SH S.FULANI II (SHIYAR S/FULANI II)',
				'UNDER TREE SHADE ADAMARE, TAMBAGARKA (ADAMARE, TAMBAGARKA S/UMAU ADAMARE)',
				'UNDER TREE SHADE SHIYAR KAURA (SHIYAR KAURA)'
			];
		}
	}