<?php
namespace App\Services\PollingUnit\Gwadabawa;
	
	class GidanKaya
	{
		
		function __construct()
		{
			# code...
			$this->pollingUnits =  $this->pollingUnits();
		}

		public function pollingUnits(){
			return [
				'PRIMARY SCHOOL MAKARANTA (MAKARANTA SHIYAR MAGAJI)',
				'UNDER TREE, LUKUMAWA OPEN SPACE (LUKUMAWA SHIYAR MAGAJI)',
				'UNDER TREE, SHIYAR BAURA OPEN SPACE (DAN FILI SHIYAR BAURA)',
				'FILIN INJIN, SHIYAR BAURA',
				'UNDER TREE, TAKALMAWA OPEN SPACE (SHIYAR HAKIMI TAKALMAWA)',
				'NEAR JUMUAT MOSQUE (SHIYAR HAKIM KILILAWA)',
				'PRIMARY SCHOOL ASIBITI/YARGADA (ASIBITI YAR GADA MULELA)',
				'SHIYAR HAKIMI, GALADIMAN TSABRE',
				'NEAR MOSQUE DAN GWAYA/K.DAUDU (SHIYAR HAKIMI GALADIMA TSIBIRI)',
				'PRIMARY SCHOOL MARINNAWA G. DOGAZA (ASIBITI MARI WAWA G/DOGAZA)',
				'PRIMARY SCHOOL DAN FANGA/TALHI (MAKARANTA DAN FANGA TALHI)',
				'FILIN GWARA (GWARA /DAWCHA)',
				'UNDER TREE SHADE TUDUN MAI DUKUSA (SHIYAR HAKIMI TUDUN MAIDUSA)',
				'UNDER TREE SHADE GIDAN DUTSI R./ADUW (SHIYAR HAKIMI GIDAN DUTSI)',
				'FILIN HAKIMI (SHIYAR HAKIMI GIDAN BIRGAU)',
				'NEAR MOSQUE KAURAR KAYAMA (SHIYAR HAIKIM KAURA KAYAMA)',
				'UNDER TREE SHADE MAKANTA, SH MAGAJI (SHIYAR MAGAJI MAKARANTA)'
			];
		}
	}