<?php
namespace App\Services\PollingUnit\Gwadabawa;
	
	class Gigane
	{
		
		function __construct()
		{
			# code...
			$this->pollingUnits =  $this->pollingUnits();
		}

		public function pollingUnits(){
			return [
				'NEAR MOSQUE SHIYAR MAGAJI (SHIYAR MAGAJI)',
				'PRIMARY SCHOOL KARANBI (KARANBI)',
				'UNDER TREE SHADE SHIYAR TUDU (SHIYAR TUDU)',
				'UNDER TREE SHADE, SHIYAR SAMRI NEAR WELL (SHIYAR SAMRI)',
				'ISLAMIYYA SCHOOL (SHIYAR SALIHU)',
				'SHIYAR BAICI OPEN SPACE (SHIYAR BAICI)',
				'PRIMARY SCHOOL TUNGAR NOMA (TUNGAR NOMA)',
				'PRY SCH, SAKAMARU',
				'GIDAN RANA, GIDAN RANA',
				'LABCHEDI, LABCHEDI',
				'PRIMARY SCHOOL GAMARU (GAMARU TUNGAR MALAM)',
				'NEAR JUMUAT MOSQUE TUNKURU DIKKO (TUNKURU DIKKO)',
				'PRIMARY SCHOOL, OPP. PH CARE (SHIYAR GALADIMA)',
				'NEAR JUMUAT MOSQUE SH. TUDU MELI (SHIYAR TUDU)',
				'YOLABALE, YOLABALE',
				'NEAR MOSQUE/TREE SHADE GWARGWAWO (GWARGWAWO)',
				'UNDER TREE SHADE SHIYAR LIMAN (SHIYAR LIMAN)',
				'G. MAIDAMMA, GIDAN MAIDAMMA'
			];
		}
	}