<?php
namespace App\Services\PollingUnit\Gwadabawa;
	
	class Gwadabawa
	{
		
		function __construct()
		{
			# code...
			$this->pollingUnits =  $this->pollingUnits();
		}

		public function pollingUnits(){
			return [
				'TSOHOWAR MAGINA, SH. GALADIMA/MULLELA',
				'TSOHOWAR MAGINA, SHIYAR GALADIMA MULLELA I',
				'TSOHOWAR MAGINA, SHIYAR GALADIMA MULLELA II',
				'YAN ALEWA BAYAN GIDAN ALTU,',
				'YAN ALEWA BAYAN GIDAN BELLO',
				'TAMBARI M.P.S, SHIYAR TAWAYAWA I',
				'TAMBARI M.P.S, SHIYAR TAWAYAWA II',
				'TAMBARI M.P.S, SHIYAR TAWAYAWA III',
				'MAITURARE M.P.S, SH. MAGAJI ALJANA',
				'MAITURARE M.P.S, SH. MAGAJI D/JANA',
				'N.O.A OFFICE, SH TUDU/DANZARAWA',
				'GABAN MASALLACI (SH/D/ZAKARA, SH/TUDU)',
				'J.S.S GWADABAWA, SH. S. FAWA I',
				'INSIDE THE SCHOOL, J.S.S GWADABAWA, SH. S. FAWA (JSS GWAD. SH/S.FAWA II)',
				'UNDER TREE SHADE SHIYAR SARKIN YAKI (SHIYAR S/YAKI RANGANDA)',
				'PRIMARY SCHOOL TSOLAWO (TSOLAWO, TSOLAWO)',
				'PRIMARY SCHOOL GAWO (GAWO GWANBULLA)',
				'PRY SCH, ABDALO',
				'TSAKAR GARI, TUDUN DOKI',
				'NEAR POL WARE GIDAN IDALTU (OLD PRI. SCH. GIDAN IDATU)',
				'HOSPITAL, CHANCHA',
				'PRY SCH, CHANCHA',
				'UNDER TREE SHADE TSAKAR GARI (TSAKAR GARI TAKARAWA)',
				'NEAR ISLAMIYYA SCHOOL (TSOHUWAR MAGINA K/ATIKU)',
				'UNDER TREE SHADE SHIYAR MAKERA (SH/MAKERA RANGANDA)',
				'BAYAN GIDAN ALTU, SHIYAR YANALEWA',
				'TAMBARI M.P.S, SHIYAR TAWAYAWA',
				'MAITURARE M.P.S, DAN ALJANNA'
			];
		}
	}