<?php

namespace App\Services\PollingUnit\Wamakko;
/**
* this class will reurn polling units of this class
*/
class Dundaye_Gumburawa
{
	
	function __construct()
	{
		$this->pollingUnits = $this->pollingUnits();
	}

	protected function pollingUnits()
	{
		return [
			'ALONG THE ROAD SIDE BINDIGAWA(BINDIGAWA)',
			'MPS DUNDAYE (DANTAWA)',
			'MPS (DUNDAYE FILING DATSA)',
			'TOWN CENTRE KANEN TURU (KANIN TURU)',
			'UNDER THE TREE GAWON TOMO (GAWON TOMD)',
			'ALONG THE ROAD SIADE GIDAN AKU (GIDAN DAN AKU)',
			'UNDER THE TREE GIDAN DAN IDI (GIDAN DAN IDDI)',
			'GINIGA OPEN SPACE (GINIGA)',
			'MPS (GUMBURAWA)',
			'AN OPEN SPACE KANAN TURU (KANEN TURU)',
			'UNDER THE TREE MAGANAWA (MAGINAWA)',
			'ALONG THE ROAD SIDE SHIYAR MAGAJI (SH. MAGAJI)',
			'AN OPEN SPACE (SH. HAMMA)',
			'MODEL PRIMARY SCHOOL (SIRI)',
			'MPS (TAMBARANGA)',
			'PRIMARY SCHOOL (TANGWALE)',
			'ALONG THE ROAD SIDE (JNR. STAFF QTRS)',
			'UNDER THE TREE (SNR. STAFF QTRS)',
			'NEAR YARA (UNGUWAR LALLE)',
			'ALONG THE ROAD SIDE NEAR MARKET (YAR KANTA)',
			'MPS (YARLABBE I)',
			'MDDES PRIMARY SCHOOL (YARLEBBE II)',
			'DISPENSARY (SHIYAR HAKIMI YAR LABBE III)',
			'UNDER THE TREE (KANEN TURU MASALACI)',
			'AN OPEN SPACE (KANEN TURU HAUSAWA)',
			'ALONG THE ROAD SIDE (GWARGAWO)',
			'AN OPEN SPACE (GIDAN DAN JADA)'
		];
	}
}